spring:
  application:
    name: tools
  
  datasource:
    url: jdbc:postgresql://localhost:5432/gruzomarket
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
      location: ${java.io.tmpdir}
  
  mail:
    host: localhost
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}

  thymeleaf:
    cache: false                     # Отключить кэш для разработки
    prefix: classpath:/templates/    # Где искать шаблоны
    suffix: .html                    # Расширение файлов
    mode: HTML                       # Режим HTML
    encoding: UTF-8                  # Кодировка

  # Настройки для статических ресурсов (CSS, JS, картинки):
  web:
    resources:
      static-locations:
        - classpath:/static/         # Стандартное место
        - classpath:/public/         # Альтернативное место
        - classpath:/resources/
        - file:./uploads/  # Еще одно альтернативное
      cache:
        period: 0                    # Для разработки - без кэширования

  # Для Windows/Linux различия в путях:
  mvc:
    static-path-pattern: /**

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    display-request-duration: true

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN:8400149455:AAGyqhpjx3SLgioc57HpqAM75TWoSvre6k4}
  chat:
    id: ${TELEGRAM_CHAT_ID:-5019285628}

